version: '3.3'

services:
  object-detector:
    image:  $APP_NAME
    network_mode: bridge
    links:
      - "inference-server"
    ipc: host
    privileged: true
    depends_on:
      - inference-server
      - ssdlite_mobilenet_object
    environment:
      - INFERENCE_HOST=inference-server
      - INFERENCE_PORT=8501
      - MODEL_PATH=/models/ssdlite_mobilenet/ssdlite-mobilenet-v2-tpu
      - MODEL_INPUT_SIZE=300x300
      - OBJECT_LIST_PATH=/model/objects.txt
      - DEBUG=y
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ssdlite_mobilenet_object:/model:ro
      - /tmp:/output
      - /var/run/dbus:/var/run/dbus:rw
      - /var/run/statuscache:/var/run/statuscache:rw
      - /usr/lib/libstatuscache.so.1:/usr/lib/libstatuscache.so
    devices:
      - /dev/datacache0:/dev/datacache0:rw

  inference-server:
    image: axisecp/larod-inference-server:2.3.0.test-api.4.0pre5-armv7hf-ubuntu20.04
    network_mode: bridge
    command: /usr/bin/larod-inference-server -p 8501 -j 4 -c testdata/server.pem -k testdata/server.key
    privileged: true
    ipc: host
    depends_on:
      - ssdlite_mobilenet_object
    expose:
      - 8501
    volumes:
      - ssdlite_mobilenet_object:/models/ssdlite_mobilenet
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /tmp:/tmp

  ssdlite_mobilenet_object:
    image: axisecp/acap-dl-models:ssdlite-mobilenet-v2
    restart: 'no'
    volumes:
      - ssdlite_mobilenet_object:/model

volumes:
  ssdlite_mobilenet_object: {}
