version: '3.3'

services:
  object-detector:
    image: axisecp/acap4-object-detector-cpp:1.1.0-armv7hf
    ipc: host
    depends_on:
      - inference-server
      - ssdlite_mobilenet_object
    environment:
      - INFERENCE_HOST=inference-server
      - INFERENCE_PORT=$INFERENCE_PORT
      - LD_LIBRARY_PATH=/host/lib
      - MODEL_PATH=/models/ssdlite_mobilenet/ssdlite-mobilenet-v2-tpu
      - MODEL_INPUT_SIZE=300x300
      - OBJECT_LIST_PATH=/model/objects.txt
      - DEBUG=y
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /lib:/host/lib
      - ssdlite_mobilenet_object:/model:ro
      - /tmp:/output
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /var/run/statuscache:/var/run/statuscache
    devices:
      - /dev/datacache0:/dev/datacache0:rw

  inference-server:
#    image: axisecp/larod-inference-server:2.1.0-armv7hf
    image: axisecp/larod-inference-server:2.1.0.test-armv7hf
#    command: /usr/bin/larod-inference-server -p $INFERENCE_PORT -j 1
    command: /usr/bin/larod-inference-server -p $INFERENCE_PORT -j 1 -c testdata/server.pem -k testdata/server.key
    ipc: host
    depends_on:
      - ssdlite_mobilenet_object
    expose:
      - $INFERENCE_PORT
    volumes:
      - ssdlite_mobilenet_object:/models/ssdlite_mobilenet
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /tmp:/tmp
      - /usr/lib/liblarod.so.1:/usr/lib/liblarod.so.1
      - /usr/lib/liblarod.so.1:/usr/lib/liblarod.so.1.0

  ssdlite_mobilenet_object:
    image: axisecp/acap-dl-models:ssdlite-mobilenet-v2
    restart: 'no'
    volumes:
      - ssdlite_mobilenet_object:/model

volumes:
  ssdlite_mobilenet_object: {}
