#!/bin/sh

DOCKER_CLI=/usr/local/bin/docker

load_images() {
	images=(${MODEL_NAME} ${INFERENC_SERVER_IMAGE} ${APP_NAME})
	tar_files=(model.tar runtime.tar app.tar)
	
	for i in 0 1 2
	do
		DOCKER_IMAGE=$(${DOCKER_CLI} image ls -q ${images[$i]})
		if [ x"${DOCKER_IMAGE}" != x"" ] ; then
    	echo "Found: ${images[$i]}"
		else
      echo "Not found: start loading.. ${images[$i]}"
		  echo "${DOCKER_CLI} load -i ${tar_files[$i]}"
		fi
	done
	#/usr/local/bin/docker load -i runtime.tar
	#/usr/local/bin/docker load -i app.tar
	#/usr/local/bin/docker load -i model.tar
}

stop_containers()  {
  ${DOCKER_CLI} compose down
  exit 0
}

# cd to script directory
cd -P -- "$(dirname -- "$0")" || {
  echo "Error: Could not change directory"
  exit 1
}

# Trap SIGINT and SIGTERM
trap 'stop_containers' 2 15

source ./env.config

load_images

${DOCKER_CLI} compose --env-file "./env.config" up

while true; do
  sleep 1
done
