#!/bin/sh

. ./env.config
DOCKER_CLI=/usr/local/bin/docker

load_images() {
  DOCKER_IMAGE=$(${DOCKER_CLI} image ls -q $1)
  if [ x"${DOCKER_IMAGE}" != x"" ] ; then
    echo "Found: $1"
  else
    echo "Not found: start loading $1 .."
    ${DOCKER_CLI} load -i $2
  fi
}

stop_containers()  {
  ${DOCKER_CLI} compose down
  exit 0
}

# cd to script directory
cd -P -- "$(dirname -- "$0")" || {
  echo "Error: Could not change directory"
  exit 1
}

# Trap SIGINT and SIGTERM
trap 'stop_containers' 2 15

load_images ${MODEL_NAME} model.tar
load_images ${INFERENCE_SERVER_IMAGE} runtime.tar
load_images ${APP_NAME} app.tar

${DOCKER_CLI} compose --env-file "./env.config" up

while true; do
  sleep 1
done
