version: '3.3'

services:
  capture-example-app:
    image: $APP_IMAGE
    ipc: "host"
    privileged: true
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
      - DEBUG=y
    volumes:
      - /usr/lib/libstatuscache.so.1:/usr/lib/libstatuscache.so
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:rw
      - /var/run/statuscache:/var/run/statuscache:rw
      # uncomment for opencv 4.2
      # - /usr/lib/libopencv_videoio.so.4.2.0:/usr/lib/libopencv_videoio.so.4.2
      # - /usr/lib/libstatuscache.so.1:/usr/lib/libstatuscache.so.1
    devices:
      - /dev/datacache0:/dev/datacache0:rw

