# Setup and run docker containers for streaming video inference on camera using TPU

version: '2.0'
services:
  inference-client:
    image: axisecp/inference-client:1.1.0-armv7hf-ubuntu19.10
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100k"
    depends_on:
      - inference-server
      - ssdlite_mobilenet_object
    environment:
      - INFERENCE_HOST=inference-server
      - INFERENCE_PORT=8501
#      - LD_LIBRARY_PATH=/host/lib
      - MODEL_PATH=/model/ssdlite-mobilenet-v2-tpu
      - MODEL_INPUT_SIZE=300x300
      - OBJECT_LIST_PATH=/model/objects.txt
      - DEBUG=y
    volumes:
      - /etc/localtime:/etc/localtime:ro
#      - /lib:/host/lib
      - ssdlite_mobilenet_object:/model:ro
      - /tmp:/output
      - /var/run/statuscache:/var/run/statuscache
      - /var/run/dbus:/var/run/dbus:rw
      - /usr/lib/libopencv_videoio.so.4.2.0:/usr/lib/libopencv_videoio.so.4.2
      - /usr/lib/libdl.so.2:/usr/lib/libdl.so.2
      - /usr/lib/libpthread.so.0:/usr/lib/libpthread.so.0
      - /usr/lib/librt.so.1:/usr/lib/librt.so.1
      - /usr/lib/libsystemd.so.0:/usr/lib/libsystemd.so.0
      - /usr/lib/libstatuscache.so.1:/usr/lib/libstatuscache.so.1
      - /usr/lib/libvdostream.so.1:/usr/lib/libvdostream.so.1
      - /usr/lib/libgobject-2.0.so.0:/usr/lib/libgobject-2.0.so.0
      - /usr/lib/libglib-2.0.so.0:/usr/lib/libglib-2.0.so.0
      - /usr/lib/libstdc++.so.6:/usr/lib/libstdc++.so.6
      - /usr/lib/libgcc_s.so.1:/usr/lib/libgcc_s.so.1
      - /usr/lib/libc.so.6:/usr/lib/libc.so.6
      - /usr/lib/libcap.so.2:/usr/lib/libcap.so.2
      - /usr/lib/libfido.so.1:/usr/lib/libfido.so.1
      - /usr/lib/libgio-2.0.so.0:/usr/lib/libgio-2.0.so.0
      - /usr/lib/libffi.so.6:/usr/lib/libffi.so.6
      - /usr/lib/libffi.so.7:/usr/lib/libffi.so.7
      - /usr/lib/libpcre.so.1:/usr/lib/libpcre.so.1
      - /usr/lib/libm.so.6:/usr/lib/libm.so.6
      - /usr/lib/libgmodule-2.0.so.0:/usr/lib/libgmodule-2.0.so.0
      - /usr/lib/libz.so.1:/usr/lib/libz.so.1
      - /usr/lib/libresolv.so.2:/usr/lib/libresolv.so.2
    devices:
      - /dev/datacache0:/dev/datacache0:rw

  inference-server:
    image: axisecp/larod-inference-server:2.1.1-api.4.0-pre3-armv7hf-ubuntu19.10
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100k"
    command: /usr/bin/larod-inference-server -p 8501 -j 1
    depends_on:
      - ssdlite_mobilenet_object
    expose:
      - 8501
    volumes:
      - ssdlite_mobilenet_object:/model:ro
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /tmp:/tmp

  ssdlite_mobilenet_object:
    image: axisecp/acap-dl-models:ssdlite-mobilenet-v2
    restart: 'no'
    volumes:
      - ssdlite_mobilenet_object:/model

volumes:
  ssdlite_mobilenet_object: {}
