# This is a basic workflow to help you get started with Actions

name: Axis-CICD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    ###

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Runs a single command using the runners shell
    - name: Login to dockerhub axis account
      run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASS }}

    # Run build script for capture app
    - name: Bulid capture_app application
      run: |
        echo Add other actions to build,
        cd ./opencv-capture-app/app
        chmod 777 build.sh
        ./build.sh docker-sandbox.se.axis.com/rapid/arm32v8/capture_app_test
        
    # Run build script for capture app
    - name: Bulid object-detector-cpp application
      run: |
        echo Add other actions to build,
        cd ./object-detector-cpp/app
        chmod 777 build.sh
        ./build.sh docker-sandbox.se.axis.com/rapid/arm32v8/capture_app_test


          
